version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - ldconfig -p | grep libfontconfig
      - npm install
  pre_build:
    commands:
      - apt-get install bzip2
      - curl -LO https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
      - tar xf phantomjs-2.1.1-linux-x86_64.tar.bz2
      - ldd ./phantomjs-2.1.1-linux-x86_64/bin/phantomjs
      - cp /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 .
      - cp /usr/lib/x86_64-linux-gnu/libfreetype.so.6 .
      - cp /lib/x86_64-linux-gnu/libexpat.so.1 .
  build:
    commands:
      - npm run deploy
artifacts:
  type: zip
  files:
    - /usr/lib/x86_64-linux-gnu/libfontconfig.so.1
    - serverless-output.yaml
