version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  pre_build:
    commands:
    

      
#      - apt-get install bzip2
#      - curl -LO https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
#      - tar xf phantomjs-2.1.1-linux-x86_64.tar.bz2
#      - ldd ./phantomjs-2.1.1-linux-x86_64/bin/phantomjs
    
      # Bundle required system libraries that aren't available on the Lambda runtime AMI
      - mkdir ./lib
      - cp /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 ./lib
      - cp /usr/lib/x86_64-linux-gnu/libfreetype.so.6 ./lib
      - cp /lib/x86_64-linux-gnu/libexpat.so.1 ./lib
      - cp /usr/lib/x86_64-linux-gnu/libpng16.so.16 ./lib
      - cp /lib/x86_64-linux-gnu/libz.so.1 ./lib

#      - ls -l /etc/fonts
#      - ls -l /usr/share/fonts
      - mkdir ./fonts
      - cp -a /etc/fonts/. ./fonts
      - cp -a /usr/share/fonts/. ./fonts
      - mkdir -p ./tmp/fonts-cache
      
#      - mkdir ./fonts
#      - mkdir ./fonts/share
#      - cp -a /etc/fonts/. ./fonts
#      - cp -a /usr/share/fonts/. ./fonts/share
      
#      - env
#      - ap t-get install bzip2
#      - curl -LO https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
#      - tar xf phantomjs-2.1.1-linux-x86_64.tar.bz2
#      - ldd ./phantomjs-2.1.1-linux-x86_64/bin/phantomjs
#      - mkdir ./lib
#      - cp /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 ./lib
#      - cp /usr/lib/x86_64-linux-gnu/libfreetype.so.6 ./lib
#      - cp /lib/x86_64-linux-gnu/libexpat.so.1 ./lib
#      - apt-get install libpng16-16
#      - ldd /usr/lib/x86_64-linux-gnu/libpng16.so.16
#      - cp /usr/lib/x86_64-linux-gnu/libpng16.so.16 ./lib
#      - dpkg -L zlib1g
#      - curl -LO https://www.zlib.net/fossils/zlib-1.2.9.tar.gz
#      - tar -xvf ./zlib-1.2.9.tar.gz
#      - cd ./zlib-1.2.9
#      - ./configure; make; make install
#      - cd ../
#      - ldd /usr/local/lib/libz.so.1.2.9
#      - cp /usr/local/lib/libz.so.1.2.9 ./lib
  build:
    commands:
      - npm run deploy
artifacts:
  type: zip
  files:
    - serverless-output.yaml
