version: 0.1
phases:
  install:
    commands:
      - apt-get update && apt-get -y install libfontconfig1
      - npm install
  pre_build:
    commands:
      - npm test
  build:
    commands:
      - npm run deploy
artifacts:
  type: zip
  files:
    - serverless-output.yaml
