version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - ldconfig -p | grep libfontconfig
      - npm install
  pre_build:
    commands:
      - yum install -y bzip2 tar
      - curl -LO https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
      - tar xf phantomjs-2.1.1-linux-x86_64.tar.bz2
      - ldd ./phantomjs-2.1.1-linux-x86_64/bin/phantomjs 
  build:
    commands:
      - npm run deploy
artifacts:
  type: zip
  files:
    - serverless-output.yaml
