version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - ldconfig -p | grep libfontconfig
      - npm install
  pre_build:
    commands:
      - ls
#      - env
#      - apt-get install bzip2
#      - curl -LO https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
#      - tar xf phantomjs-2.1.1-linux-x86_64.tar.bz2
#      - ldd ./phantomjs-2.1.1-linux-x86_64/bin/phantomjs
#      - mkdir ./lib
#      - cp /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 ./lib
#      - cp /usr/lib/x86_64-linux-gnu/libfreetype.so.6 ./lib
#      - cp /lib/x86_64-linux-gnu/libexpat.so.1 ./lib
#      - apt-get install libpng16-16
#      - ldd /usr/lib/x86_64-linux-gnu/libpng16.so.16
#      - cp /usr/lib/x86_64-linux-gnu/libpng16.so.16 ./lib
#      - dpkg -L zlib1g
#      - curl -LO https://www.zlib.net/fossils/zlib-1.2.9.tar.gz
#      - tar -xvf ./zlib-1.2.9.tar.gz
#      - cd ./zlib-1.2.9
#      - ./configure; make; make install
#      - cd ../
#      - ldd /usr/local/lib/libz.so.1.2.9
#      - cp /usr/local/lib/libz.so.1.2.9 ./lib
  build:
    commands:
      - npm run deploy
artifacts:
  type: zip
  files:
    - /usr/lib/x86_64-linux-gnu/libfontconfig.so.1
    - serverless-output.yaml
